CREATE DATABASE if NOT EXISTS `PEDIDOS` COLLATE utf8_general_ci;
CREATE DATABASE if NOT EXISTS `PAGAMENTOS` COLLATE utf8_general_ci;
CREATE DATABASE if NOT EXISTS `FINANCEIRA` COLLATE utf8_general_ci;